/**
 * https://api.exchange.coinbase.com/products
 */

interface CoinbaseProduct {
  id: string;
  base_currency: string;
  quote_currency: string;
  display_name: string;
}

export const COINBASE_PRODUCTS: CoinbaseProduct[] = [
  {
    id: "RPL-USD",
    base_currency: "RPL",
    quote_currency: "USD",
    display_name: "RPL-USD",
  },
  {
    id: "AERGO-USD",
    base_currency: "AERGO",
    quote_currency: "USD",
    display_name: "AERGO-USD",
  },
  {
    id: "ETC-USD",
    base_currency: "ETC",
    quote_currency: "USD",
    display_name: "ETC-USD",
  },
  {
    id: "QUICK-USD",
    base_currency: "QUICK",
    quote_currency: "USD",
    display_name: "QUICK-USD",
  },
  {
    id: "YFII-USD",
    base_currency: "YFII",
    quote_currency: "USD",
    display_name: "YFII-USD",
  },
  {
    id: "AIOZ-USD",
    base_currency: "AIOZ",
    quote_currency: "USD",
    display_name: "AIOZ-USD",
  },
  {
    id: "GODS-USD",
    base_currency: "GODS",
    quote_currency: "USD",
    display_name: "GODS-USD",
  },
  {
    id: "MSOL-USD",
    base_currency: "MSOL",
    quote_currency: "USD",
    display_name: "MSOL-USD",
  },
  {
    id: "TRAC-USD",
    base_currency: "TRAC",
    quote_currency: "USD",
    display_name: "TRAC-USD",
  },
  {
    id: "XTZ-USD",
    base_currency: "XTZ",
    quote_currency: "USD",
    display_name: "XTZ-USD",
  },
  {
    id: "00-USD",
    base_currency: "00",
    quote_currency: "USD",
    display_name: "00-USD",
  },
  {
    id: "GYEN-USD",
    base_currency: "GYEN",
    quote_currency: "USD",
    display_name: "GYEN-USD",
  },
  {
    id: "AGLD-USD",
    base_currency: "AGLD",
    quote_currency: "USD",
    display_name: "AGLD-USD",
  },
  {
    id: "ORCA-USD",
    base_currency: "ORCA",
    quote_currency: "USD",
    display_name: "ORCA-USD",
  },
  {
    id: "DESO-USD",
    base_currency: "DESO",
    quote_currency: "USD",
    display_name: "DESO-USD",
  },
  {
    id: "STX-USD",
    base_currency: "STX",
    quote_currency: "USD",
    display_name: "STX-USD",
  },
  {
    id: "ATOM-USD",
    base_currency: "ATOM",
    quote_currency: "USD",
    display_name: "ATOM-USD",
  },
  {
    id: "METIS-USD",
    base_currency: "METIS",
    quote_currency: "USD",
    display_name: "METIS-USD",
  },
  {
    id: "NMR-USD",
    base_currency: "NMR",
    quote_currency: "USD",
    display_name: "NMR-USD",
  },
  {
    id: "BNT-USD",
    base_currency: "BNT",
    quote_currency: "USD",
    display_name: "BNT-USD",
  },
  {
    id: "ADA-USD",
    base_currency: "ADA",
    quote_currency: "USD",
    display_name: "ADA-USD",
  },
  {
    id: "CVC-USD",
    base_currency: "CVC",
    quote_currency: "USD",
    display_name: "CVC-USD",
  },
  {
    id: "DAR-USD",
    base_currency: "DAR",
    quote_currency: "USD",
    display_name: "DAR-USD",
  },
  {
    id: "USDT-USD",
    base_currency: "USDT",
    quote_currency: "USD",
    display_name: "USDT-USD",
  },
  {
    id: "SYN-USD",
    base_currency: "SYN",
    quote_currency: "USD",
    display_name: "SYN-USD",
  },
  {
    id: "MPL-USD",
    base_currency: "MPL",
    quote_currency: "USD",
    display_name: "MPL-USD",
  },
  {
    id: "VARA-USD",
    base_currency: "VARA",
    quote_currency: "USD",
    display_name: "VARA-USD",
  },
  {
    id: "WAMPL-USD",
    base_currency: "WAMPL",
    quote_currency: "USD",
    display_name: "WAMPL-USD",
  },
  {
    id: "RENDER-USD",
    base_currency: "RENDER",
    quote_currency: "USD",
    display_name: "RENDER/USD",
  },
  {
    id: "UNFI-USD",
    base_currency: "UNFI",
    quote_currency: "USD",
    display_name: "UNFI-USD",
  },
  {
    id: "DDX-USD",
    base_currency: "DDX",
    quote_currency: "USD",
    display_name: "DDX-USD",
  },
  {
    id: "BTC-USD",
    base_currency: "BTC",
    quote_currency: "USD",
    display_name: "BTC-USD",
  },
  {
    id: "INJ-USD",
    base_currency: "INJ",
    quote_currency: "USD",
    display_name: "INJ-USD",
  },
  {
    id: "SKL-USD",
    base_currency: "SKL",
    quote_currency: "USD",
    display_name: "SKL-USD",
  },
  {
    id: "COVAL-USD",
    base_currency: "COVAL",
    quote_currency: "USD",
    display_name: "COVAL-USD",
  },
  {
    id: "ZEN-USD",
    base_currency: "ZEN",
    quote_currency: "USD",
    display_name: "ZEN-USD",
  },
  {
    id: "ZEC-USD",
    base_currency: "ZEC",
    quote_currency: "USD",
    display_name: "ZEC-USD",
  },
  {
    id: "MIR-USD",
    base_currency: "MIR",
    quote_currency: "USD",
    display_name: "MIR-USD",
  },
  {
    id: "HONEY-USD",
    base_currency: "HONEY",
    quote_currency: "USD",
    display_name: "HONEY-USD",
  },
  {
    id: "GRT-USD",
    base_currency: "GRT",
    quote_currency: "USD",
    display_name: "GRT-USD",
  },
  {
    id: "POLS-USD",
    base_currency: "POLS",
    quote_currency: "USD",
    display_name: "POLS-USD",
  },
  {
    id: "ORN-USD",
    base_currency: "ORN",
    quote_currency: "USD",
    display_name: "ORN-USD",
  },
  {
    id: "SUPER-USD",
    base_currency: "SUPER",
    quote_currency: "USD",
    display_name: "SUPER-USD",
  },
  {
    id: "ATA-USD",
    base_currency: "ATA",
    quote_currency: "USD",
    display_name: "ATA-USD",
  },
  {
    id: "REN-USD",
    base_currency: "REN",
    quote_currency: "USD",
    display_name: "REN-USD",
  },
  {
    id: "NEON-USD",
    base_currency: "NEON",
    quote_currency: "USD",
    display_name: "NEON/USD",
  },
  {
    id: "UMA-USD",
    base_currency: "UMA",
    quote_currency: "USD",
    display_name: "UMA-USD",
  },
  {
    id: "PYR-USD",
    base_currency: "PYR",
    quote_currency: "USD",
    display_name: "PYR-USD",
  },
  {
    id: "ACS-USD",
    base_currency: "ACS",
    quote_currency: "USD",
    display_name: "ACS-USD",
  },
  {
    id: "QI-USD",
    base_currency: "QI",
    quote_currency: "USD",
    display_name: "QI-USD",
  },
  {
    id: "APT-USD",
    base_currency: "APT",
    quote_currency: "USD",
    display_name: "APT-USD",
  },
  {
    id: "CGLD-USD",
    base_currency: "CGLD",
    quote_currency: "USD",
    display_name: "CGLD-USD",
  },
  {
    id: "FX-USD",
    base_currency: "FX",
    quote_currency: "USD",
    display_name: "FX-USD",
  },
  {
    id: "OGN-USD",
    base_currency: "OGN",
    quote_currency: "USD",
    display_name: "OGN-USD",
  },
  {
    id: "LOOM-USD",
    base_currency: "LOOM",
    quote_currency: "USD",
    display_name: "LOOM-USD",
  },
  {
    id: "SHPING-USD",
    base_currency: "SHPING",
    quote_currency: "USD",
    display_name: "SHPING-USD",
  },
  {
    id: "T-USD",
    base_currency: "T",
    quote_currency: "USD",
    display_name: "T-USD",
  },
  {
    id: "NKN-USD",
    base_currency: "NKN",
    quote_currency: "USD",
    display_name: "NKN-USD",
  },
  {
    id: "KSM-USD",
    base_currency: "KSM",
    quote_currency: "USD",
    display_name: "KSM-USD",
  },
  {
    id: "TONE-USD",
    base_currency: "TONE",
    quote_currency: "USD",
    display_name: "TONE-USD",
  },
  {
    id: "RAI-USD",
    base_currency: "RAI",
    quote_currency: "USD",
    display_name: "RAI-USD",
  },
  {
    id: "UPI-USD",
    base_currency: "UPI",
    quote_currency: "USD",
    display_name: "UPI-USD",
  },
  {
    id: "VOXEL-USD",
    base_currency: "VOXEL",
    quote_currency: "USD",
    display_name: "VOXEL-USD",
  },
  {
    id: "SAFE-USD",
    base_currency: "SAFE",
    quote_currency: "USD",
    display_name: "SAFE/USD",
  },
  {
    id: "AVT-USD",
    base_currency: "AVT",
    quote_currency: "USD",
    display_name: "AVT-USD",
  },
  {
    id: "IOTX-USD",
    base_currency: "IOTX",
    quote_currency: "USD",
    display_name: "IOTX-USD",
  },
  {
    id: "ETH-USD",
    base_currency: "ETH",
    quote_currency: "USD",
    display_name: "ETH-USD",
  },
  {
    id: "FIDA-USD",
    base_currency: "FIDA",
    quote_currency: "USD",
    display_name: "FIDA-USD",
  },
  {
    id: "DREP-USD",
    base_currency: "DREP",
    quote_currency: "USD",
    display_name: "DREP-USD",
  },
  {
    id: "FIL-USD",
    base_currency: "FIL",
    quote_currency: "USD",
    display_name: "FIL-USD",
  },
  {
    id: "BAT-USD",
    base_currency: "BAT",
    quote_currency: "USD",
    display_name: "BAT-USD",
  },
  {
    id: "CORECHAIN-USD",
    base_currency: "CORECHAIN",
    quote_currency: "USD",
    display_name: "CORECHAIN/USD",
  },
  {
    id: "CTSI-USD",
    base_currency: "CTSI",
    quote_currency: "USD",
    display_name: "CTSI-USD",
  },
  {
    id: "BAL-USD",
    base_currency: "BAL",
    quote_currency: "USD",
    display_name: "BAL-USD",
  },
  {
    id: "REQ-USD",
    base_currency: "REQ",
    quote_currency: "USD",
    display_name: "REQ-USD",
  },
  {
    id: "RARI-USD",
    base_currency: "RARI",
    quote_currency: "USD",
    display_name: "RARI-USD",
  },
  {
    id: "SPELL-USD",
    base_currency: "SPELL",
    quote_currency: "USD",
    display_name: "SPELL-USD",
  },
  {
    id: "QSP-USD",
    base_currency: "QSP",
    quote_currency: "USD",
    display_name: "QSP-USD",
  },
  {
    id: "GAL-USD",
    base_currency: "GAL",
    quote_currency: "USD",
    display_name: "GAL-USD",
  },
  {
    id: "INV-USD",
    base_currency: "INV",
    quote_currency: "USD",
    display_name: "INV-USD",
  },
  {
    id: "SNX-USD",
    base_currency: "SNX",
    quote_currency: "USD",
    display_name: "SNX-USD",
  },
  {
    id: "CLV-USD",
    base_currency: "CLV",
    quote_currency: "USD",
    display_name: "CLV-USD",
  },
  {
    id: "MANA-USD",
    base_currency: "MANA",
    quote_currency: "USD",
    display_name: "MANA-USD",
  },
  {
    id: "OMNI-USD",
    base_currency: "OMNI",
    quote_currency: "USD",
    display_name: "OMNI/USD",
  },
  {
    id: "ROSE-USD",
    base_currency: "ROSE",
    quote_currency: "USD",
    display_name: "ROSE-USD",
  },
  {
    id: "SHIB-USD",
    base_currency: "SHIB",
    quote_currency: "USD",
    display_name: "SHIB-USD",
  },
  {
    id: "SEI-USD",
    base_currency: "SEI",
    quote_currency: "USD",
    display_name: "SEI-USD",
  },
  {
    id: "ALGO-USD",
    base_currency: "ALGO",
    quote_currency: "USD",
    display_name: "ALGO-USD",
  },
  {
    id: "PRIME-USD",
    base_currency: "PRIME",
    quote_currency: "USD",
    display_name: "PRIME-USD",
  },
  {
    id: "QNT-USD",
    base_currency: "QNT",
    quote_currency: "USD",
    display_name: "QNT-USD",
  },
  {
    id: "MATIC-USD",
    base_currency: "MATIC",
    quote_currency: "USD",
    display_name: "MATIC-USD",
  },
  {
    id: "LRDS-USD",
    base_currency: "LRDS",
    quote_currency: "USD",
    display_name: "LRDS/USD",
  },
  {
    id: "VGX-USD",
    base_currency: "VGX",
    quote_currency: "USD",
    display_name: "VGX-USD",
  },
  {
    id: "OCEAN-USD",
    base_currency: "OCEAN",
    quote_currency: "USD",
    display_name: "OCEAN-USD",
  },
  {
    id: "FLR-USD",
    base_currency: "FLR",
    quote_currency: "USD",
    display_name: "FLR-USD",
  },
  {
    id: "ANKR-USD",
    base_currency: "ANKR",
    quote_currency: "USD",
    display_name: "ANKR-USD",
  },
  {
    id: "ERN-USD",
    base_currency: "ERN",
    quote_currency: "USD",
    display_name: "ERN-USD",
  },
  {
    id: "AST-USD",
    base_currency: "AST",
    quote_currency: "USD",
    display_name: "AST-USD",
  },
  {
    id: "MASK-USD",
    base_currency: "MASK",
    quote_currency: "USD",
    display_name: "MASK-USD",
  },
  {
    id: "STRK-USD",
    base_currency: "STRK",
    quote_currency: "USD",
    display_name: "STRK/USD",
  },
  {
    id: "OP-USD",
    base_currency: "OP",
    quote_currency: "USD",
    display_name: "OP-USD",
  },
  {
    id: "SNT-USD",
    base_currency: "SNT",
    quote_currency: "USD",
    display_name: "SNT-USD",
  },
  {
    id: "BIT-USD",
    base_currency: "BIT",
    quote_currency: "USD",
    display_name: "BIT-USD",
  },
  {
    id: "BAND-USD",
    base_currency: "BAND",
    quote_currency: "USD",
    display_name: "BAND-USD",
  },
  {
    id: "JASMY-USD",
    base_currency: "JASMY",
    quote_currency: "USD",
    display_name: "JASMY-USD",
  },
  {
    id: "SD-USD",
    base_currency: "SD",
    quote_currency: "USD",
    display_name: "SD/USD",
  },
  {
    id: "ACH-USD",
    base_currency: "ACH",
    quote_currency: "USD",
    display_name: "ACH-USD",
  },
  {
    id: "SUSHI-USD",
    base_currency: "SUSHI",
    quote_currency: "USD",
    display_name: "SUSHI-USD",
  },
  {
    id: "GTC-USD",
    base_currency: "GTC",
    quote_currency: "USD",
    display_name: "GTC-USD",
  },
  {
    id: "DIMO-USD",
    base_currency: "DIMO",
    quote_currency: "USD",
    display_name: "DIMO-USD",
  },
  {
    id: "PLU-USD",
    base_currency: "PLU",
    quote_currency: "USD",
    display_name: "PLU-USD",
  },
  {
    id: "PUNDIX-USD",
    base_currency: "PUNDIX",
    quote_currency: "USD",
    display_name: "PUNDIX-USD",
  },
  {
    id: "EGLD-USD",
    base_currency: "EGLD",
    quote_currency: "USD",
    display_name: "EGLD-USD",
  },
  {
    id: "LIT-USD",
    base_currency: "LIT",
    quote_currency: "USD",
    display_name: "LIT-USD",
  },
  {
    id: "IDEX-USD",
    base_currency: "IDEX",
    quote_currency: "USD",
    display_name: "IDEX-USD",
  },
  {
    id: "CRV-USD",
    base_currency: "CRV",
    quote_currency: "USD",
    display_name: "CRV-USD",
  },
  {
    id: "SUKU-USD",
    base_currency: "SUKU",
    quote_currency: "USD",
    display_name: "SUKU-USD",
  },
  {
    id: "COMP-USD",
    base_currency: "COMP",
    quote_currency: "USD",
    display_name: "COMP-USD",
  },
  {
    id: "LOKA-USD",
    base_currency: "LOKA",
    quote_currency: "USD",
    display_name: "LOKA-USD",
  },
  {
    id: "MNDE-USD",
    base_currency: "MNDE",
    quote_currency: "USD",
    display_name: "MNDE-USD",
  },
  {
    id: "BONK-USD",
    base_currency: "BONK",
    quote_currency: "USD",
    display_name: "BONK-USD",
  },
  {
    id: "AVAX-USD",
    base_currency: "AVAX",
    quote_currency: "USD",
    display_name: "AVAX-USD",
  },
  {
    id: "DNT-USD",
    base_currency: "DNT",
    quote_currency: "USD",
    display_name: "DNT-USD",
  },
  {
    id: "VTHO-USD",
    base_currency: "VTHO",
    quote_currency: "USD",
    display_name: "VTHO-USD",
  },
  {
    id: "LSETH-USD",
    base_currency: "LSETH",
    quote_currency: "USD",
    display_name: "LSETH-USD",
  },
  {
    id: "HNT-USD",
    base_currency: "HNT",
    quote_currency: "USD",
    display_name: "HNT-USD",
  },
  {
    id: "WAXL-USD",
    base_currency: "WAXL",
    quote_currency: "USD",
    display_name: "WAXL-USD",
  },
  {
    id: "MUSE-USD",
    base_currency: "MUSE",
    quote_currency: "USD",
    display_name: "MUSE-USD",
  },
  {
    id: "UST-USD",
    base_currency: "UST",
    quote_currency: "USD",
    display_name: "UST-USD",
  },
  {
    id: "MATH-USD",
    base_currency: "MATH",
    quote_currency: "USD",
    display_name: "MATH-USD",
  },
  {
    id: "WBTC-USD",
    base_currency: "WBTC",
    quote_currency: "USD",
    display_name: "WBTC-USD",
  },
  {
    id: "STG-USD",
    base_currency: "STG",
    quote_currency: "USD",
    display_name: "STG-USD",
  },
  {
    id: "DASH-USD",
    base_currency: "DASH",
    quote_currency: "USD",
    display_name: "DASH-USD",
  },
  {
    id: "AUDIO-USD",
    base_currency: "AUDIO",
    quote_currency: "USD",
    display_name: "AUDIO-USD",
  },
  {
    id: "GHST-USD",
    base_currency: "GHST",
    quote_currency: "USD",
    display_name: "GHST-USD",
  },
  {
    id: "AXL-USD",
    base_currency: "AXL",
    quote_currency: "USD",
    display_name: "AXL-USD",
  },
  {
    id: "KNC-USD",
    base_currency: "KNC",
    quote_currency: "USD",
    display_name: "KNC-USD",
  },
  {
    id: "AKT-USD",
    base_currency: "AKT",
    quote_currency: "USD",
    display_name: "AKT/USD",
  },
  {
    id: "CELR-USD",
    base_currency: "CELR",
    quote_currency: "USD",
    display_name: "CELR-USD",
  },
  {
    id: "DOT-USD",
    base_currency: "DOT",
    quote_currency: "USD",
    display_name: "DOT-USD",
  },
  {
    id: "GUSD-USD",
    base_currency: "GUSD",
    quote_currency: "USD",
    display_name: "GUSD-USD",
  },
  {
    id: "FARM-USD",
    base_currency: "FARM",
    quote_currency: "USD",
    display_name: "FARM-USD",
  },
  {
    id: "DOGE-USD",
    base_currency: "DOGE",
    quote_currency: "USD",
    display_name: "DOGE-USD",
  },
  {
    id: "PERP-USD",
    base_currency: "PERP",
    quote_currency: "USD",
    display_name: "PERP-USD",
  },
  {
    id: "1INCH-USD",
    base_currency: "1INCH",
    quote_currency: "USD",
    display_name: "1INCH-USD",
  },
  {
    id: "LTC-USD",
    base_currency: "LTC",
    quote_currency: "USD",
    display_name: "LTC-USD",
  },
  {
    id: "ENS-USD",
    base_currency: "ENS",
    quote_currency: "USD",
    display_name: "ENS-USD",
  },
  {
    id: "RLC-USD",
    base_currency: "RLC",
    quote_currency: "USD",
    display_name: "RLC-USD",
  },
  {
    id: "CBETH-USD",
    base_currency: "CBETH",
    quote_currency: "USD",
    display_name: "cbETH-USD",
  },
  {
    id: "DEXT-USD",
    base_currency: "DEXT",
    quote_currency: "USD",
    display_name: "DEXT-USD",
  },
  {
    id: "XYO-USD",
    base_currency: "XYO",
    quote_currency: "USD",
    display_name: "XYO-USD",
  },
  {
    id: "ICP-USD",
    base_currency: "ICP",
    quote_currency: "USD",
    display_name: "ICP-USD",
  },
  {
    id: "MKR-USD",
    base_currency: "MKR",
    quote_currency: "USD",
    display_name: "MKR-USD",
  },
  {
    id: "PNG-USD",
    base_currency: "PNG",
    quote_currency: "USD",
    display_name: "PNG-USD",
  },
  {
    id: "NEST-USD",
    base_currency: "NEST",
    quote_currency: "USD",
    display_name: "NEST-USD",
  },
  {
    id: "BLUR-USD",
    base_currency: "BLUR",
    quote_currency: "USD",
    display_name: "BLUR-USD",
  },
  {
    id: "WLUNA-USD",
    base_currency: "WLUNA",
    quote_currency: "USD",
    display_name: "WLUNA-USD",
  },
  {
    id: "TIME-USD",
    base_currency: "TIME",
    quote_currency: "USD",
    display_name: "TIME-USD",
  },
  {
    id: "SOL-USD",
    base_currency: "SOL",
    quote_currency: "USD",
    display_name: "SOL-USD",
  },
  {
    id: "LQTY-USD",
    base_currency: "LQTY",
    quote_currency: "USD",
    display_name: "LQTY-USD",
  },
  {
    id: "ALICE-USD",
    base_currency: "ALICE",
    quote_currency: "USD",
    display_name: "ALICE-USD",
  },
  {
    id: "HOPR-USD",
    base_currency: "HOPR",
    quote_currency: "USD",
    display_name: "HOPR-USD",
  },
  {
    id: "MCO2-USD",
    base_currency: "MCO2",
    quote_currency: "USD",
    display_name: "MCO2-USD",
  },
  {
    id: "MTL-USD",
    base_currency: "MTL",
    quote_currency: "USD",
    display_name: "MTL-USD",
  },
  {
    id: "NCT-USD",
    base_currency: "NCT",
    quote_currency: "USD",
    display_name: "NCT-USD",
  },
  {
    id: "INDEX-USD",
    base_currency: "INDEX",
    quote_currency: "USD",
    display_name: "INDEX-USD",
  },
  {
    id: "C98-USD",
    base_currency: "C98",
    quote_currency: "USD",
    display_name: "C98-USD",
  },
  {
    id: "TRU-USD",
    base_currency: "TRU",
    quote_currency: "USD",
    display_name: "TRU-USD",
  },
  {
    id: "CVX-USD",
    base_currency: "CVX",
    quote_currency: "USD",
    display_name: "CVX-USD",
  },
  {
    id: "MEDIA-USD",
    base_currency: "MEDIA",
    quote_currency: "USD",
    display_name: "MEDIA-USD",
  },
  {
    id: "MONA-USD",
    base_currency: "MONA",
    quote_currency: "USD",
    display_name: "MONA-USD",
  },
  {
    id: "FIS-USD",
    base_currency: "FIS",
    quote_currency: "USD",
    display_name: "FIS-USD",
  },
  {
    id: "RGT-USD",
    base_currency: "RGT",
    quote_currency: "USD",
    display_name: "RGT-USD",
  },
  {
    id: "TRIBE-USD",
    base_currency: "TRIBE",
    quote_currency: "USD",
    display_name: "TRIBE-USD",
  },
  {
    id: "KAVA-USD",
    base_currency: "KAVA",
    quote_currency: "USD",
    display_name: "KAVA-USD",
  },
  {
    id: "BOBA-USD",
    base_currency: "BOBA",
    quote_currency: "USD",
    display_name: "BOBA-USD",
  },
  {
    id: "AAVE-USD",
    base_currency: "AAVE",
    quote_currency: "USD",
    display_name: "AAVE-USD",
  },
  {
    id: "ALCX-USD",
    base_currency: "ALCX",
    quote_currency: "USD",
    display_name: "ALCX-USD",
  },
  {
    id: "ANT-USD",
    base_currency: "ANT",
    quote_currency: "USD",
    display_name: "ANT-USD",
  },
  {
    id: "BLZ-USD",
    base_currency: "BLZ",
    quote_currency: "USD",
    display_name: "BLZ-USD",
  },
  {
    id: "GFI-USD",
    base_currency: "GFI",
    quote_currency: "USD",
    display_name: "GFI-USD",
  },
  {
    id: "AERO-USD",
    base_currency: "AERO",
    quote_currency: "USD",
    display_name: "AERO-USD",
  },
  {
    id: "XLM-USD",
    base_currency: "XLM",
    quote_currency: "USD",
    display_name: "XLM-USD",
  },
  {
    id: "IMX-USD",
    base_currency: "IMX",
    quote_currency: "USD",
    display_name: "IMX-USD",
  },
  {
    id: "BUSD-USD",
    base_currency: "BUSD",
    quote_currency: "USD",
    display_name: "BUSD-USD",
  },
  {
    id: "PRQ-USD",
    base_currency: "PRQ",
    quote_currency: "USD",
    display_name: "PRQ-USD",
  },
  {
    id: "BCH-USD",
    base_currency: "BCH",
    quote_currency: "USD",
    display_name: "BCH-USD",
  },
  {
    id: "CTX-USD",
    base_currency: "CTX",
    quote_currency: "USD",
    display_name: "CTX-USD",
  },
  {
    id: "HIGH-USD",
    base_currency: "HIGH",
    quote_currency: "USD",
    display_name: "HIGH-USD",
  },
  {
    id: "API3-USD",
    base_currency: "API3",
    quote_currency: "USD",
    display_name: "API3-USD",
  },
  {
    id: "SAND-USD",
    base_currency: "SAND",
    quote_currency: "USD",
    display_name: "SAND-USD",
  },
  {
    id: "ABT-USD",
    base_currency: "ABT",
    quote_currency: "USD",
    display_name: "ABT-USD",
  },
  {
    id: "WCFG-USD",
    base_currency: "WCFG",
    quote_currency: "USD",
    display_name: "WCFG-USD",
  },
  {
    id: "OOKI-USD",
    base_currency: "OOKI",
    quote_currency: "USD",
    display_name: "OOKI-USD",
  },
  {
    id: "ARKM-USD",
    base_currency: "ARKM",
    quote_currency: "USD",
    display_name: "ARKM/USD",
  },
  {
    id: "APE-USD",
    base_currency: "APE",
    quote_currency: "USD",
    display_name: "APE-USD",
  },
  {
    id: "REP-USD",
    base_currency: "REP",
    quote_currency: "USD",
    display_name: "REP-USD",
  },
  {
    id: "SUI-USD",
    base_currency: "SUI",
    quote_currency: "USD",
    display_name: "SUI-USD",
  },
  {
    id: "COTI-USD",
    base_currency: "COTI",
    quote_currency: "USD",
    display_name: "COTI-USD",
  },
  {
    id: "TNSR-USD",
    base_currency: "TNSR",
    quote_currency: "USD",
    display_name: "TNSR/USD",
  },
  {
    id: "TIA-USD",
    base_currency: "TIA",
    quote_currency: "USD",
    display_name: "TIA-USD",
  },
  {
    id: "MOBILE-USD",
    base_currency: "MOBILE",
    quote_currency: "USD",
    display_name: "MOBILE/USD",
  },
  {
    id: "ENJ-USD",
    base_currency: "ENJ",
    quote_currency: "USD",
    display_name: "ENJ-USD",
  },
  {
    id: "LPT-USD",
    base_currency: "LPT",
    quote_currency: "USD",
    display_name: "LPT-USD",
  },
  {
    id: "FOX-USD",
    base_currency: "FOX",
    quote_currency: "USD",
    display_name: "FOX-USD",
  },
  {
    id: "AMP-USD",
    base_currency: "AMP",
    quote_currency: "USD",
    display_name: "AMP-USD",
  },
  {
    id: "HBAR-USD",
    base_currency: "HBAR",
    quote_currency: "USD",
    display_name: "HBAR-USD",
  },
  {
    id: "EURC-USD",
    base_currency: "EURC",
    quote_currency: "USD",
    display_name: "EURC/USD",
  },
  {
    id: "AURORA-USD",
    base_currency: "AURORA",
    quote_currency: "USD",
    display_name: "AURORA-USD",
  },
  {
    id: "HFT-USD",
    base_currency: "HFT",
    quote_currency: "USD",
    display_name: "HFT-USD",
  },
  {
    id: "KARRAT-USD",
    base_currency: "KARRAT",
    quote_currency: "USD",
    display_name: "KARRAT/USD",
  },
  {
    id: "RONIN-USD",
    base_currency: "RONIN",
    quote_currency: "USD",
    display_name: "RONIN/USD",
  },
  {
    id: "PIRATE-USD",
    base_currency: "PIRATE",
    quote_currency: "USD",
    display_name: "PIRATE/USD",
  },
  {
    id: "ZRX-USD",
    base_currency: "ZRX",
    quote_currency: "USD",
    display_name: "ZRX-USD",
  },
  {
    id: "STORJ-USD",
    base_currency: "STORJ",
    quote_currency: "USD",
    display_name: "STORJ-USD",
  },
  {
    id: "OMG-USD",
    base_currency: "OMG",
    quote_currency: "USD",
    display_name: "OMG-USD",
  },
  {
    id: "MDT-USD",
    base_currency: "MDT",
    quote_currency: "USD",
    display_name: "MDT-USD",
  },
  {
    id: "PYUSD-USD",
    base_currency: "PYUSD",
    quote_currency: "USD",
    display_name: "PYUSD-USD",
  },
  {
    id: "TVK-USD",
    base_currency: "TVK",
    quote_currency: "USD",
    display_name: "TVK-USD",
  },
  {
    id: "ONDO-USD",
    base_currency: "ONDO",
    quote_currency: "USD",
    display_name: "ONDO-USD",
  },
  {
    id: "TRB-USD",
    base_currency: "TRB",
    quote_currency: "USD",
    display_name: "TRB-USD",
  },
  {
    id: "BADGER-USD",
    base_currency: "BADGER",
    quote_currency: "USD",
    display_name: "BADGER-USD",
  },
  {
    id: "BTRST-USD",
    base_currency: "BTRST",
    quote_currency: "USD",
    display_name: "BTRST-USD",
  },
  {
    id: "ZETA-USD",
    base_currency: "ZETA",
    quote_currency: "USD",
    display_name: "ZETA-USD",
  },
  {
    id: "ARPA-USD",
    base_currency: "ARPA",
    quote_currency: "USD",
    display_name: "ARPA-USD",
  },
  {
    id: "XCN-USD",
    base_currency: "XCN",
    quote_currency: "USD",
    display_name: "XCN-USD",
  },
  {
    id: "ILV-USD",
    base_currency: "ILV",
    quote_currency: "USD",
    display_name: "ILV-USD",
  },
  {
    id: "MINA-USD",
    base_currency: "MINA",
    quote_currency: "USD",
    display_name: "MINA-USD",
  },
  {
    id: "OXT-USD",
    base_currency: "OXT",
    quote_currency: "USD",
    display_name: "OXT-USD",
  },
  {
    id: "FORTH-USD",
    base_currency: "FORTH",
    quote_currency: "USD",
    display_name: "FORTH-USD",
  },
  {
    id: "DAI-USD",
    base_currency: "DAI",
    quote_currency: "USD",
    display_name: "DAI-USD",
  },
  {
    id: "RBN-USD",
    base_currency: "RBN",
    quote_currency: "USD",
    display_name: "RBN-USD",
  },
  {
    id: "BIGTIME-USD",
    base_currency: "BIGTIME",
    quote_currency: "USD",
    display_name: "BIGTIME-USD",
  },
  {
    id: "LINK-USD",
    base_currency: "LINK",
    quote_currency: "USD",
    display_name: "LINK-USD",
  },
  {
    id: "ARB-USD",
    base_currency: "ARB",
    quote_currency: "USD",
    display_name: "ARB-USD",
  },
  {
    id: "XRP-USD",
    base_currency: "XRP",
    quote_currency: "USD",
    display_name: "XRP-USD",
  },
  {
    id: "POND-USD",
    base_currency: "POND",
    quote_currency: "USD",
    display_name: "POND-USD",
  },
  {
    id: "PRO-USD",
    base_currency: "PRO",
    quote_currency: "USD",
    display_name: "PRO-USD",
  },
  {
    id: "OSMO-USD",
    base_currency: "OSMO",
    quote_currency: "USD",
    display_name: "OSMO-USD",
  },
  {
    id: "VET-USD",
    base_currency: "VET",
    quote_currency: "USD",
    display_name: "VET-USD",
  },
  {
    id: "GMT-USD",
    base_currency: "GMT",
    quote_currency: "USD",
    display_name: "GMT-USD",
  },
  {
    id: "LCX-USD",
    base_currency: "LCX",
    quote_currency: "USD",
    display_name: "LCX-USD",
  },
  {
    id: "GST-USD",
    base_currency: "GST",
    quote_currency: "USD",
    display_name: "GST-USD",
  },
  {
    id: "ALEPH-USD",
    base_currency: "ALEPH",
    quote_currency: "USD",
    display_name: "ALEPH-USD",
  },
  {
    id: "JUP-USD",
    base_currency: "JUP",
    quote_currency: "USD",
    display_name: "JUP-USD",
  },
  {
    id: "GLM-USD",
    base_currency: "GLM",
    quote_currency: "USD",
    display_name: "GLM-USD",
  },
  {
    id: "RAD-USD",
    base_currency: "RAD",
    quote_currency: "USD",
    display_name: "RAD-USD",
  },
  {
    id: "ELA-USD",
    base_currency: "ELA",
    quote_currency: "USD",
    display_name: "ELA-USD",
  },
  {
    id: "SHDW-USD",
    base_currency: "SHDW",
    quote_currency: "USD",
    display_name: "SHDW/USD",
  },
  {
    id: "RARE-USD",
    base_currency: "RARE",
    quote_currency: "USD",
    display_name: "RARE-USD",
  },
  {
    id: "CHZ-USD",
    base_currency: "CHZ",
    quote_currency: "USD",
    display_name: "CHZ-USD",
  },
  {
    id: "SWFTC-USD",
    base_currency: "SWFTC",
    quote_currency: "USD",
    display_name: "SWFTC-USD",
  },
  {
    id: "BOND-USD",
    base_currency: "BOND",
    quote_currency: "USD",
    display_name: "BOND-USD",
  },
  {
    id: "SEAM-USD",
    base_currency: "SEAM",
    quote_currency: "USD",
    display_name: "SEAM-USD",
  },
  {
    id: "PLA-USD",
    base_currency: "PLA",
    quote_currency: "USD",
    display_name: "PLA-USD",
  },
  {
    id: "KRL-USD",
    base_currency: "KRL",
    quote_currency: "USD",
    display_name: "KRL-USD",
  },
  {
    id: "DIA-USD",
    base_currency: "DIA",
    quote_currency: "USD",
    display_name: "DIA-USD",
  },
  {
    id: "MAGIC-USD",
    base_currency: "MAGIC",
    quote_currency: "USD",
    display_name: "MAGIC-USD",
  },
  {
    id: "RNDR-USD",
    base_currency: "RNDR",
    quote_currency: "USD",
    display_name: "RNDR-USD",
  },
  {
    id: "MLN-USD",
    base_currency: "MLN",
    quote_currency: "USD",
    display_name: "MLN-USD",
  },
  {
    id: "FLOW-USD",
    base_currency: "FLOW",
    quote_currency: "USD",
    display_name: "FLOW-USD",
  },
  {
    id: "ZRO-USD",
    base_currency: "ZRO",
    quote_currency: "USD",
    display_name: "ZRO/USD",
  },
  {
    id: "ASM-USD",
    base_currency: "ASM",
    quote_currency: "USD",
    display_name: "ASM-USD",
  },
  {
    id: "DYP-USD",
    base_currency: "DYP",
    quote_currency: "USD",
    display_name: "DYP-USD",
  },
  {
    id: "RLY-USD",
    base_currency: "RLY",
    quote_currency: "USD",
    display_name: "RLY-USD",
  },
  {
    id: "MUSD-USD",
    base_currency: "MUSD",
    quote_currency: "USD",
    display_name: "MUSD-USD",
  },
  {
    id: "FET-USD",
    base_currency: "FET",
    quote_currency: "USD",
    display_name: "FET-USD",
  },
  {
    id: "SYLO-USD",
    base_currency: "SYLO",
    quote_currency: "USD",
    display_name: "SYLO-USD",
  },
  {
    id: "PAX-USD",
    base_currency: "PAX",
    quote_currency: "USD",
    display_name: "PAX-USD",
  },
  {
    id: "MXC-USD",
    base_currency: "MXC",
    quote_currency: "USD",
    display_name: "MXC-USD",
  },
  {
    id: "YFI-USD",
    base_currency: "YFI",
    quote_currency: "USD",
    display_name: "YFI-USD",
  },
  {
    id: "DRIFT-USD",
    base_currency: "DRIFT",
    quote_currency: "USD",
    display_name: "DRIFT/USD",
  },
  {
    id: "BLAST-USD",
    base_currency: "BLAST",
    quote_currency: "USD",
    display_name: "BLAST/USD",
  },
  {
    id: "POWR-USD",
    base_currency: "POWR",
    quote_currency: "USD",
    display_name: "POWR-USD",
  },
  {
    id: "GALA-USD",
    base_currency: "GALA",
    quote_currency: "USD",
    display_name: "GALA-USD",
  },
  {
    id: "CRO-USD",
    base_currency: "CRO",
    quote_currency: "USD",
    display_name: "CRO-USD",
  },
  {
    id: "SPA-USD",
    base_currency: "SPA",
    quote_currency: "USD",
    display_name: "SPA-USD",
  },
  {
    id: "VELO-USD",
    base_currency: "VELO",
    quote_currency: "USD",
    display_name: "VELO-USD",
  },
  {
    id: "POLY-USD",
    base_currency: "POLY",
    quote_currency: "USD",
    display_name: "POLY-USD",
  },
  {
    id: "KEEP-USD",
    base_currency: "KEEP",
    quote_currency: "USD",
    display_name: "KEEP-USD",
  },
  {
    id: "GNO-USD",
    base_currency: "GNO",
    quote_currency: "USD",
    display_name: "GNO-USD",
  },
  {
    id: "UNI-USD",
    base_currency: "UNI",
    quote_currency: "USD",
    display_name: "UNI-USD",
  },
  {
    id: "JTO-USD",
    base_currency: "JTO",
    quote_currency: "USD",
    display_name: "JTO-USD",
  },
  {
    id: "CRPT-USD",
    base_currency: "CRPT",
    quote_currency: "USD",
    display_name: "CRPT-USD",
  },
  {
    id: "FORT-USD",
    base_currency: "FORT",
    quote_currency: "USD",
    display_name: "FORT-USD",
  },
  {
    id: "A8-USD",
    base_currency: "A8",
    quote_currency: "USD",
    display_name: "A8/USD",
  },
  {
    id: "MULTI-USD",
    base_currency: "MULTI",
    quote_currency: "USD",
    display_name: "MULTI-USD",
  },
  {
    id: "LRC-USD",
    base_currency: "LRC",
    quote_currency: "USD",
    display_name: "LRC-USD",
  },
  {
    id: "NEAR-USD",
    base_currency: "NEAR",
    quote_currency: "USD",
    display_name: "NEAR-USD",
  },
  {
    id: "AXS-USD",
    base_currency: "AXS",
    quote_currency: "USD",
    display_name: "AXS-USD",
  },
  {
    id: "AUCTION-USD",
    base_currency: "AUCTION",
    quote_currency: "USD",
    display_name: "AUCTION-USD",
  },
  {
    id: "NU-USD",
    base_currency: "NU",
    quote_currency: "USD",
    display_name: "NU-USD",
  },
  {
    id: "BICO-USD",
    base_currency: "BICO",
    quote_currency: "USD",
    display_name: "BICO-USD",
  },
  {
    id: "LDO-USD",
    base_currency: "LDO",
    quote_currency: "USD",
    display_name: "LDO-USD",
  },
  {
    id: "EOS-USD",
    base_currency: "EOS",
    quote_currency: "USD",
    display_name: "EOS-USD",
  },
];
